version: "3.9"

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: the-bazaar-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0 --port 5173
    profiles:
      - dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: the-bazaar-prod
    ports:
      - "8080:80"
    environment:
      - VITE_THIRDWEB_CLIENT_ID=${VITE_THIRDWEB_CLIENT_ID}
      - VITE_SEPOLIA_TOKEN_CONTRACT_ADDRESS=${VITE_SEPOLIA_TOKEN_CONTRACT_ADDRESS}
      - VITE_SEPOLIA_MARKETPLACE_CONTRACT_ADDRESS=${VITE_SEPOLIA_MARKETPLACE_CONTRACT_ADDRESS}
      - VITE_SEPOLIA_TOKENSHOP_CONTRACT_ADDRESS=${VITE_SEPOLIA_TOKENSHOP_CONTRACT_ADDRESS}
      - VITE_APP_PINATA_API_KEY=${VITE_APP_PINATA_API_KEY}
      - VITE_APP_PINATA_SECRET_KEY=${VITE_APP_PINATA_SECRET_KEY}
    profiles:
      - prod
