#!/bin/sh
set -eu

cat <<EOF >/usr/share/nginx/html/runtime-config.js
window.__BAZAAR_ENV__ = {
  VITE_THIRDWEB_CLIENT_ID: "${VITE_THIRDWEB_CLIENT_ID:-}",
  VITE_SEPOLIA_TOKEN_CONTRACT_ADDRESS: "${VITE_SEPOLIA_TOKEN_CONTRACT_ADDRESS:-}",
  VITE_SEPOLIA_MARKETPLACE_CONTRACT_ADDRESS: "${VITE_SEPOLIA_MARKETPLACE_CONTRACT_ADDRESS:-}",
  VITE_SEPOLIA_TOKENSHOP_CONTRACT_ADDRESS: "${VITE_SEPOLIA_TOKENSHOP_CONTRACT_ADDRESS:-}",
  VITE_APP_PINATA_API_KEY: "${VITE_APP_PINATA_API_KEY:-}",
  VITE_APP_PINATA_SECRET_KEY: "${VITE_APP_PINATA_SECRET_KEY:-}"
};
EOF
